using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentHistories;

public class DocumentHistoryManager : DocumentHistoryManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentHistoryManager(IDocumentHistoryRepository documentHistoryRepository) : base(documentHistoryRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}