using HC.Documents;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentHistories;

public class DocumentHistory : DocumentHistoryBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentHistory()
    {
    }

    public DocumentHistory(Guid id, Guid documentId, Guid? fromUser, Guid toUser, string action, string? comment = null) : base(id, documentId, fromUser, toUser, action, comment)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}