using HC.SurveySessions;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.SurveyFiles;

public class SurveyFile : SurveyFileBase
{
    //<suite-custom-code-autogenerated>
    protected SurveyFile()
    {
    }

    public SurveyFile(Guid id, Guid surveySessionId, string uploaderType, string fileName, string filePath, int fileSize, string mimeType, string fileType) : base(id, surveySessionId, uploaderType, fileName, filePath, fileSize, mimeType, fileType)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}