using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SurveyFiles;

public class SurveyFileManager : SurveyFileManagerBase
{
    //<suite-custom-code-autogenerated>
    public SurveyFileManager(ISurveyFileRepository surveyFileRepository) : base(surveyFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}