using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Notifications;

public class Notification : NotificationBase
{
    //<suite-custom-code-autogenerated>
    protected Notification()
    {
    }

    public Notification(Guid id, string title, string content, string sourceType, string eventType, string relatedType, string priority, string? relatedId = null) : base(id, title, content, sourceType, eventType, relatedType, priority, relatedId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}