using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.WorkflowStepAssignments;

public class WorkflowStepAssignmentManager : WorkflowStepAssignmentManagerBase
{
    //<suite-custom-code-autogenerated>
    public WorkflowStepAssignmentManager(IWorkflowStepAssignmentRepository workflowStepAssignmentRepository) : base(workflowStepAssignmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}