using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SurveyResults;

public class SurveyResultManager : SurveyResultManagerBase
{
    //<suite-custom-code-autogenerated>
    public SurveyResultManager(ISurveyResultRepository surveyResultRepository) : base(surveyResultRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}