using HC.SurveyCriterias;
using HC.SurveySessions;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.SurveyResults;

public class SurveyResult : SurveyResultBase
{
    //<suite-custom-code-autogenerated>
    protected SurveyResult()
    {
    }

    public SurveyResult(Guid id, Guid surveyCriteriaId, Guid surveySessionId, int rating) : base(id, surveyCriteriaId, surveySessionId, rating)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}