using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.UserDepartments;

public class UserDepartmentManager : UserDepartmentManagerBase
{
    //<suite-custom-code-autogenerated>
    public UserDepartmentManager(IUserDepartmentRepository userDepartmentRepository) : base(userDepartmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}