using HC.Departments;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.UserDepartments;

public class UserDepartment : UserDepartmentBase
{
    //<suite-custom-code-autogenerated>
    protected UserDepartment()
    {
    }

    public UserDepartment(Guid id, Guid departmentId, Guid userId, bool isPrimary, bool isActive) : base(id, departmentId, userId, isPrimary, isActive)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}