using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Notifications;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.Notifications;

public class NotificationsAppService : NotificationsAppServiceBase, INotificationsAppService
{
    //<suite-custom-code-autogenerated>
    public NotificationsAppService(INotificationRepository notificationRepository, NotificationManager notificationManager, IDistributedCache<NotificationDownloadTokenCacheItem, string> downloadTokenCache) : base(notificationRepository, notificationManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}