using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.ProjectTaskDocuments;

public class ProjectTaskDocumentManager : ProjectTaskDocumentManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProjectTaskDocumentManager(IProjectTaskDocumentRepository projectTaskDocumentRepository) : base(projectTaskDocumentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}