using HC.ProjectTasks;
using HC.Documents;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.ProjectTaskDocuments;

public class ProjectTaskDocument : ProjectTaskDocumentBase
{
    //<suite-custom-code-autogenerated>
    protected ProjectTaskDocument()
    {
    }

    public ProjectTaskDocument(Guid id, Guid projectTaskId, Guid documentId, string documentPurpose) : base(id, projectTaskId, documentId, documentPurpose)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}