namespace HC.CalendarEvents;

public enum EventType
{
    MEETING,
    DEADLINE,
    REMINDER,
    WORKFLOW_ASSIGNED,
    WORKFLOW_COMPLETED,
    TASK_ASSIGNED,
    TASK_DUE_SOON,
    CHAT_MESSAGE_NEW,
    CALENDAR_INVITED,
    CALENDAR_REMINDER,
}