using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Units;

public class Unit : UnitBase
{
    //<suite-custom-code-autogenerated>
    protected Unit()
    {
    }

    public Unit(Guid id, string code, string name, int sortOrder, bool isActive) : base(id, code, name, sortOrder, isActive)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}