using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Units;

public class UnitManager : UnitManagerBase
{
    //<suite-custom-code-autogenerated>
    public UnitManager(IUnitRepository unitRepository) : base(unitRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}