using HC.Shared;
using HC.Documents;
using HC.ProjectTasks;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTaskDocuments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.ProjectTaskDocuments;

public class ProjectTaskDocumentsAppService : ProjectTaskDocumentsAppServiceBase, IProjectTaskDocumentsAppService
{
    //<suite-custom-code-autogenerated>
    public ProjectTaskDocumentsAppService(IProjectTaskDocumentRepository projectTaskDocumentRepository, ProjectTaskDocumentManager projectTaskDocumentManager, IDistributedCache<ProjectTaskDocumentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.ProjectTasks.ProjectTask, Guid> projectTaskRepository, IRepository<HC.Documents.Document, Guid> documentRepository) : base(projectTaskDocumentRepository, projectTaskDocumentManager, downloadTokenCache, projectTaskRepository, documentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}