using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.ProjectTasks;

public class ProjectTaskManager : ProjectTaskManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProjectTaskManager(IProjectTaskRepository projectTaskRepository) : base(projectTaskRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}