using HC.Projects;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.ProjectTasks;

public class ProjectTask : ProjectTaskBase
{
    //<suite-custom-code-autogenerated>
    protected ProjectTask()
    {
    }

    public ProjectTask(Guid id, Guid projectId, string code, string title, DateTime startDate, DateTime dueDate, string priority, string status, int progressPercent, string? parentTaskId = null, string? description = null) : base(id, projectId, code, title, startDate, dueDate, priority, status, progressPercent, parentTaskId, description)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}