using HC.Shared;
using Volo.Abp.Identity;
using HC.ProjectTasks;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTaskAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.ProjectTaskAssignments;

public class ProjectTaskAssignmentsAppService : ProjectTaskAssignmentsAppServiceBase, IProjectTaskAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    public ProjectTaskAssignmentsAppService(IProjectTaskAssignmentRepository projectTaskAssignmentRepository, ProjectTaskAssignmentManager projectTaskAssignmentManager, IDistributedCache<ProjectTaskAssignmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.ProjectTasks.ProjectTask, Guid> projectTaskRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(projectTaskAssignmentRepository, projectTaskAssignmentManager, downloadTokenCache, projectTaskRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}