using HC.Shared;
using Volo.Abp.Identity;
using HC.ProjectTasks;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTaskAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;

namespace HC.ProjectTaskAssignments;

public class ProjectTaskAssignmentsAppService : ProjectTaskAssignmentsAppServiceBase, IProjectTaskAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.ProjectTasks.ProjectTask, Guid> _projectTaskRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    
    public ProjectTaskAssignmentsAppService(
        IProjectTaskAssignmentRepository projectTaskAssignmentRepository, 
        ProjectTaskAssignmentManager projectTaskAssignmentManager, 
        IDistributedCache<ProjectTaskAssignmentDownloadTokenCacheItem, string> downloadTokenCache, 
        IRepository<HC.ProjectTasks.ProjectTask, Guid> projectTaskRepository, 
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus) 
        : base(projectTaskAssignmentRepository, projectTaskAssignmentManager, downloadTokenCache, projectTaskRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _projectTaskRepository = projectTaskRepository;
        _identityUserRepository = identityUserRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<ProjectTaskAssignmentDto> CreateAsync(ProjectTaskAssignmentCreateDto input)
    {
        // Call base method to create assignment
        var result = await base.CreateAsync(input);
        
        // Get project task and user information
        var projectTask = await _projectTaskRepository.GetAsync(input.ProjectTaskId);
        var assignedUser = await _identityUserRepository.GetAsync(input.UserId);
        var currentUser = CurrentUser;
        
        // Create notification with localization
        var notificationTitle = L["TaskAssigned", projectTask.Title];
        var notificationContent = L["TaskAssignedMessage", 
            projectTask.Code, 
            projectTask.Title, 
            currentUser?.UserName ?? L["System"]];
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitle,
            notificationContent,
            SourceType.TASK.ToString(),
            EventType.TASK_ASSIGNED.ToString(),
            RelatedType.TASK.ToString(),
            "NORMAL",
            projectTask.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );
        
        return result;
    }
}