using HC.Shared;
using HC.SurveyLocations;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyCriterias;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.SurveyCriterias;

public class SurveyCriteriasAppService : SurveyCriteriasAppServiceBase, ISurveyCriteriasAppService
{
    //<suite-custom-code-autogenerated>
    public SurveyCriteriasAppService(ISurveyCriteriaRepository surveyCriteriaRepository, SurveyCriteriaManager surveyCriteriaManager, IDistributedCache<SurveyCriteriaDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveyLocations.SurveyLocation, Guid> surveyLocationRepository) : base(surveyCriteriaRepository, surveyCriteriaManager, downloadTokenCache, surveyLocationRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}