using HC.Notifications;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.NotificationReceivers;

public class NotificationReceiver : NotificationReceiverBase
{
    //<suite-custom-code-autogenerated>
    protected NotificationReceiver()
    {
    }

    public NotificationReceiver(Guid id, Guid notificationId, Guid identityUserId, bool isRead, DateTime? readAt = null) : base(id, notificationId, identityUserId, isRead, readAt)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}