using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.NotificationReceivers;

public class NotificationReceiverManager : NotificationReceiverManagerBase
{
    //<suite-custom-code-autogenerated>
    public NotificationReceiverManager(INotificationReceiverRepository notificationReceiverRepository) : base(notificationReceiverRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}