using HC.Workflows;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.WorkflowTemplates;

public class WorkflowTemplate : WorkflowTemplateBase
{
    //<suite-custom-code-autogenerated>
    protected WorkflowTemplate()
    {
    }

    public WorkflowTemplate(Guid id, Guid workflowId, string code, string name, string? wordTemplatePath = null, string? contentSchema = null, string? outputFormat = null, string? signMode = null) : base(id, workflowId, code, name, wordTemplatePath, contentSchema, outputFormat, signMode)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}