using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.WorkflowTemplates;

public class WorkflowTemplateManager : WorkflowTemplateManagerBase
{
    //<suite-custom-code-autogenerated>
    public WorkflowTemplateManager(IWorkflowTemplateRepository workflowTemplateRepository) : base(workflowTemplateRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}