using HC.WorkflowDefinitions;
using HC.WorkflowDefinitions;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Workflows;

public class Workflow : WorkflowBase
{
    //<suite-custom-code-autogenerated>
    protected Workflow()
    {
    }

    public Workflow(Guid id, Guid workflowDefinitionId, string code, string name, bool isActive, string? description = null) : base(id, workflowDefinitionId, code, name, isActive, description)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}