using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Workflows;

public class WorkflowManager : WorkflowManagerBase
{
    //<suite-custom-code-autogenerated>
    public WorkflowManager(IWorkflowRepository workflowRepository) : base(workflowRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}