using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SurveyCriterias;

public class SurveyCriteriaManager : SurveyCriteriaManagerBase
{
    //<suite-custom-code-autogenerated>
    public SurveyCriteriaManager(ISurveyCriteriaRepository surveyCriteriaRepository) : base(surveyCriteriaRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}