using HC.Projects;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.ProjectMembers;

public class ProjectMember : ProjectMemberBase
{
    //<suite-custom-code-autogenerated>
    protected ProjectMember()
    {
    }

    public ProjectMember(Guid id, Guid projectId, Guid userId, string memberRole, DateTime joinedAt) : base(id, projectId, userId, memberRole, joinedAt)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}