using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.ProjectMembers;

public class ProjectMemberManager : ProjectMemberManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProjectMemberManager(IProjectMemberRepository projectMemberRepository) : base(projectMemberRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}