using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SignatureSettings;

public class SignatureSettingManager : SignatureSettingManagerBase
{
    //<suite-custom-code-autogenerated>
    public SignatureSettingManager(ISignatureSettingRepository signatureSettingRepository) : base(signatureSettingRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}