using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.SignatureSettings;

public class SignatureSetting : SignatureSettingBase
{
    //<suite-custom-code-autogenerated>
    protected SignatureSetting()
    {
    }

    public SignatureSetting(Guid id, string providerCode, ProviderType providerType, string apiEndpoint, int apiTimeout, SignType defaultSignType, bool allowElectronicSign, bool allowDigitalSign, bool requireOtp, int signWidth, int signHeight, string signedFileSuffix, bool keepOriginalFile, bool overwriteSignedFile, bool enableSignLog, bool isActive) : base(id, providerCode, providerType, apiEndpoint, apiTimeout, defaultSignType, allowElectronicSign, allowDigitalSign, requireOtp, signWidth, signHeight, signedFileSuffix, keepOriginalFile, overwriteSignedFile, enableSignLog, isActive)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}