using HC.ProjectTasks;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.ProjectTaskAssignments;

public class ProjectTaskAssignment : ProjectTaskAssignmentBase
{
    //<suite-custom-code-autogenerated>
    protected ProjectTaskAssignment()
    {
    }

    public ProjectTaskAssignment(Guid id, Guid projectTaskId, Guid userId, string assignmentRole, DateTime assignedAt, string? note = null) : base(id, projectTaskId, userId, assignmentRole, assignedAt, note)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}