using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.ProjectTaskAssignments;

public class ProjectTaskAssignmentManager : ProjectTaskAssignmentManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProjectTaskAssignmentManager(IProjectTaskAssignmentRepository projectTaskAssignmentRepository) : base(projectTaskAssignmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}