using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Positions;

public class Position : PositionBase
{
    //<suite-custom-code-autogenerated>
    protected Position()
    {
    }

    public Position(Guid id, string code, string name, int signOrder, bool isActive) : base(id, code, name, signOrder, isActive)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}