using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Positions;

public class PositionManager : PositionManagerBase
{
    //<suite-custom-code-autogenerated>
    public PositionManager(IPositionRepository positionRepository) : base(positionRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}