using HC.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.UserSignatures;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.UserSignatures;

public class UserSignaturesAppService : UserSignaturesAppServiceBase, IUserSignaturesAppService
{
    //<suite-custom-code-autogenerated>
    public UserSignaturesAppService(IUserSignatureRepository userSignatureRepository, UserSignatureManager userSignatureManager, IDistributedCache<UserSignatureDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(userSignatureRepository, userSignatureManager, downloadTokenCache, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}