using HC.Shared;
using HC.Workflows;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.WorkflowTemplates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.WorkflowTemplates;

public class WorkflowTemplatesAppService : WorkflowTemplatesAppServiceBase, IWorkflowTemplatesAppService
{
    //<suite-custom-code-autogenerated>
    public WorkflowTemplatesAppService(IWorkflowTemplateRepository workflowTemplateRepository, WorkflowTemplateManager workflowTemplateManager, IDistributedCache<WorkflowTemplateDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Workflows.Workflow, Guid> workflowRepository) : base(workflowTemplateRepository, workflowTemplateManager, downloadTokenCache, workflowRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}