using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.CalendarEvents;

public class CalendarEvent : CalendarEventBase
{
    //<suite-custom-code-autogenerated>
    protected CalendarEvent()
    {
    }

    public CalendarEvent(Guid id, string title, DateTime startTime, DateTime endTime, bool allDay, EventType eventType, RelatedType relatedType, string? description = null, string? location = null, string? relatedId = null) : base(id, title, startTime, endTime, allDay, eventType, relatedType, description, location, relatedId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}