using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.CalendarEvents;

public class CalendarEventManager : CalendarEventManagerBase
{
    //<suite-custom-code-autogenerated>
    public CalendarEventManager(ICalendarEventRepository calendarEventRepository) : base(calendarEventRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}