using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Departments;

public class Department : DepartmentBase
{
    //<suite-custom-code-autogenerated>
    protected Department()
    {
    }

    public Department(Guid id, Guid? leaderUserId, string code, string name, int level, int sortOrder, bool isActive, string? parentId = null) : base(id, leaderUserId, code, name, level, sortOrder, isActive, parentId)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}