using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Departments;

public class DepartmentManager : DepartmentManagerBase
{
    //<suite-custom-code-autogenerated>
    public DepartmentManager(IDepartmentRepository departmentRepository) : base(departmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}