using HC.Shared;
using HC.WorkflowTemplates;
using HC.Shared;
using HC.Workflows;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.WorkflowStepTemplates;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.WorkflowStepTemplates;

public class WorkflowStepTemplatesAppService : WorkflowStepTemplatesAppServiceBase, IWorkflowStepTemplatesAppService
{
    //<suite-custom-code-autogenerated>
    public WorkflowStepTemplatesAppService(IWorkflowStepTemplateRepository workflowStepTemplateRepository, WorkflowStepTemplateManager workflowStepTemplateManager, IDistributedCache<WorkflowStepTemplateDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.WorkflowTemplates.WorkflowTemplate, Guid> workflowTemplateRepository) : base(workflowStepTemplateRepository, workflowStepTemplateManager, downloadTokenCache, workflowTemplateRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}