using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.CalendarEvents;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.CalendarEvents;

public class CalendarEventsAppService : CalendarEventsAppServiceBase, ICalendarEventsAppService
{
    //<suite-custom-code-autogenerated>
    public CalendarEventsAppService(ICalendarEventRepository calendarEventRepository, CalendarEventManager calendarEventManager, IDistributedCache<CalendarEventDownloadTokenCacheItem, string> downloadTokenCache) : base(calendarEventRepository, calendarEventManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}