using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentWorkflowInstances;

public class DocumentWorkflowInstanceManager : DocumentWorkflowInstanceManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentWorkflowInstanceManager(IDocumentWorkflowInstanceRepository documentWorkflowInstanceRepository) : base(documentWorkflowInstanceRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}