using HC.Documents;
using HC.Workflows;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentWorkflowInstances;

public class DocumentWorkflowInstance : DocumentWorkflowInstanceBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentWorkflowInstance()
    {
    }

    public DocumentWorkflowInstance(Guid id, Guid documentId, Guid workflowId, Guid workflowTemplateId, Guid currentStepId, string status, DateTime startedAt, DateTime finishedAt) : base(id, documentId, workflowId, workflowTemplateId, currentStepId, status, startedAt, finishedAt)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}