using HC.MasterDatas;
using HC.Units;
using HC.Workflows;
using HC.MasterDatas;
using HC.Units;
using HC.Workflows;
using HC.MasterDatas;
using HC.Units;
using HC.Workflows;
using HC.MasterDatas;
using HC.Units;
using HC.Workflows;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Documents;

public class Document : DocumentBase
{
    //<suite-custom-code-autogenerated>
    protected Document()
    {
    }

    public Document(Guid id, Guid? fieldId, Guid? unitId, Guid? workflowId, Guid? statusId, Guid typeId, Guid urgencyLevelId, Guid secrecyLevelId, string title, DateTime completedTime, string storageNumber, string? no = null, string? currentStatus = null) : base(id, fieldId, unitId, workflowId, statusId, typeId, urgencyLevelId, secrecyLevelId, title, completedTime, storageNumber, no, currentStatus)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}