using HC.MasterDatas;
using HC.Units;
using HC.Workflows;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Documents;

public class Document : DocumentBase
{
    //<suite-custom-code-autogenerated>
    protected Document()
    {
    }

    public Document(Guid id, Guid? fieldId, Guid? unitId, Guid? workflowId, Guid? statusId, string title, DateTime completedTime, string? no = null, string? type = null, string? urgencyLevel = null, string? secrecyLevel = null, string? currentStatus = null) : base(id, fieldId, unitId, workflowId, statusId, title, completedTime, no, type, urgencyLevel, secrecyLevel, currentStatus)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}