using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SurveySessions;

public class SurveySessionManager : SurveySessionManagerBase
{
    //<suite-custom-code-autogenerated>
    public SurveySessionManager(ISurveySessionRepository surveySessionRepository) : base(surveySessionRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}