using HC.SurveyLocations;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.SurveySessions;

public class SurveySession : SurveySessionBase
{
    //<suite-custom-code-autogenerated>
    protected SurveySession()
    {
    }

    public SurveySession(Guid id, Guid surveyLocationId, DateTime surveyTime, string sessionDisplay, string? fullName = null, string? phoneNumber = null, string? patientCode = null, string? deviceType = null, string? note = null) : base(id, surveyLocationId, surveyTime, sessionDisplay, fullName, phoneNumber, patientCode, deviceType, note)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}