using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.UserSignatures;

public class UserSignatureManager : UserSignatureManagerBase
{
    //<suite-custom-code-autogenerated>
    public UserSignatureManager(IUserSignatureRepository userSignatureRepository) : base(userSignatureRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}