using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.UserSignatures;

public class UserSignature : UserSignatureBase
{
    //<suite-custom-code-autogenerated>
    protected UserSignature()
    {
    }

    public UserSignature(Guid id, Guid identityUserId, string signType, string providerCode, string signatureImage, bool isActive, string? tokenRef = null, DateTime? validFrom = null, DateTime? validTo = null) : base(id, identityUserId, signType, providerCode, signatureImage, isActive, tokenRef, validFrom, validTo)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}