using HC.Shared;
using HC.SurveySessions;
using HC.SurveyCriterias;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyResults;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.SurveyResults;

public class SurveyResultsAppService : SurveyResultsAppServiceBase, ISurveyResultsAppService
{
    //<suite-custom-code-autogenerated>
    public SurveyResultsAppService(ISurveyResultRepository surveyResultRepository, SurveyResultManager surveyResultManager, IDistributedCache<SurveyResultDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveyCriterias.SurveyCriteria, Guid> surveyCriteriaRepository, IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository) : base(surveyResultRepository, surveyResultManager, downloadTokenCache, surveyCriteriaRepository, surveySessionRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}