using HC.Documents;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentFiles;

public class DocumentFile : DocumentFileBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentFile()
    {
    }

    public DocumentFile(Guid id, Guid documentId, string name, bool isSigned, DateTime uploadedAt, string? path = null, string? hash = null) : base(id, documentId, name, isSigned, uploadedAt, path, hash)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}