using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentFiles;

public class DocumentFileManager : DocumentFileManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentFileManager(IDocumentFileRepository documentFileRepository) : base(documentFileRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}