using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.Projects;

public class ProjectManager : ProjectManagerBase
{
    //<suite-custom-code-autogenerated>
    public ProjectManager(IProjectRepository projectRepository) : base(projectRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}