using HC.Departments;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.Projects;

public class Project : ProjectBase
{
    //<suite-custom-code-autogenerated>
    protected Project()
    {
    }

    public Project(Guid id, Guid? ownerDepartmentId, string code, string name, DateTime startDate, DateTime endDate, string status, string? description = null) : base(id, ownerDepartmentId, code, name, startDate, endDate, status, description)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}