using HC.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Departments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.Departments;

public class DepartmentsAppService : DepartmentsAppServiceBase, IDepartmentsAppService
{
    //<suite-custom-code-autogenerated>
    public DepartmentsAppService(IDepartmentRepository departmentRepository, DepartmentManager departmentManager, IDistributedCache<DepartmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(departmentRepository, departmentManager, downloadTokenCache, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}