using HC.Shared;
using Volo.Abp.Identity;
using HC.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.UserDepartments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.UserDepartments;

public class UserDepartmentsAppService : UserDepartmentsAppServiceBase, IUserDepartmentsAppService
{
    //<suite-custom-code-autogenerated>
    public UserDepartmentsAppService(IUserDepartmentRepository userDepartmentRepository, UserDepartmentManager userDepartmentManager, IDistributedCache<UserDepartmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Departments.Department, Guid> departmentRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(userDepartmentRepository, userDepartmentManager, downloadTokenCache, departmentRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}