using HC.Shared;
using HC.SurveySessions;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SurveyFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.SurveyFiles;

public class SurveyFilesAppService : SurveyFilesAppServiceBase, ISurveyFilesAppService
{
    //<suite-custom-code-autogenerated>
    public SurveyFilesAppService(ISurveyFileRepository surveyFileRepository, SurveyFileManager surveyFileManager, IDistributedCache<SurveyFileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.SurveySessions.SurveySession, Guid> surveySessionRepository) : base(surveyFileRepository, surveyFileManager, downloadTokenCache, surveySessionRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}