using HC.Shared;
using Volo.Abp.Identity;
using HC.CalendarEvents;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.CalendarEventParticipants;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.CalendarEventParticipants;

public class CalendarEventParticipantsAppService : CalendarEventParticipantsAppServiceBase, ICalendarEventParticipantsAppService
{
    //<suite-custom-code-autogenerated>
    public CalendarEventParticipantsAppService(ICalendarEventParticipantRepository calendarEventParticipantRepository, CalendarEventParticipantManager calendarEventParticipantManager, IDistributedCache<CalendarEventParticipantDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.CalendarEvents.CalendarEvent, Guid> calendarEventRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(calendarEventParticipantRepository, calendarEventParticipantManager, downloadTokenCache, calendarEventRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}