using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Caching;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;

namespace HC.CalendarEventParticipants;

public class CalendarEventParticipantsAppService : CalendarEventParticipantsAppServiceBase, ICalendarEventParticipantsAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.CalendarEvents.CalendarEvent, Guid> _calendarEventRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    protected ICalendarEventParticipantRepository _calendarEventParticipantRepository;
    
    public CalendarEventParticipantsAppService(
        ICalendarEventParticipantRepository calendarEventParticipantRepository, 
        CalendarEventParticipantManager calendarEventParticipantManager, 
        IDistributedCache<CalendarEventParticipantDownloadTokenCacheItem, string> downloadTokenCache, 
        IRepository<HC.CalendarEvents.CalendarEvent, Guid> calendarEventRepository, 
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus) 
        : base(calendarEventParticipantRepository, calendarEventParticipantManager, downloadTokenCache, calendarEventRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _calendarEventRepository = calendarEventRepository;
        _identityUserRepository = identityUserRepository;
        _calendarEventParticipantRepository = calendarEventParticipantRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<CalendarEventParticipantDto> CreateAsync(CalendarEventParticipantCreateDto input)
    {
        // Call base method to create participant
        var result = await base.CreateAsync(input);
        
        // Get calendar event and user information
        var calendarEvent = await _calendarEventRepository.GetAsync(input.CalendarEventId);
        var participantUser = await _identityUserRepository.GetAsync(input.IdentityUserId);
        var currentUser = CurrentUser;
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "CalendarInvited";
        var notificationContentKey = $"CalendarInvitedMessage|{calendarEvent.Title}|{calendarEvent.StartTime:dd/MM/yyyy HH:mm}|{currentUser?.UserName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.CALENDAR.ToString(),
            HC.Notifications.EventType.CALENDAR_INVITED.ToString(),
            HC.Notifications.RelatedType.CALENDAR_EVENT.ToString(),
            "NORMAL",
            calendarEvent.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.IdentityUserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.IdentityUserId }
            }
        );
        
        return result;
    }
    
    // Override DeleteAsync to add notification logic
    public override async Task DeleteAsync(Guid id)
    {
        // Get participant info before deleting
        var participantWithNav = await _calendarEventParticipantRepository.GetWithNavigationPropertiesAsync(id);
        var calendarEvent = participantWithNav.CalendarEvent;
        var user = participantWithNav.IdentityUser;
        var currentUser = CurrentUser;
        
        // Call base method to delete participant
        await base.DeleteAsync(id);
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "CalendarInviteRemoved";
        var notificationContentKey = $"CalendarInviteRemovedMessage|{calendarEvent.Title}|{calendarEvent.StartTime:dd/MM/yyyy HH:mm}|{currentUser?.UserName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.CALENDAR.ToString(),
            HC.Notifications.EventType.CALENDAR_INVITE_REMOVED.ToString(),
            HC.Notifications.RelatedType.CALENDAR_EVENT.ToString(),
            "NORMAL",
            calendarEvent.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            user.Id,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { user.Id }
            }
        );
    }
    
    // Override UpdateAsync to add notification logic
    public override async Task<CalendarEventParticipantDto> UpdateAsync(Guid id, CalendarEventParticipantUpdateDto input)
    {
        // Call base method to update participant
        var result = await base.UpdateAsync(id, input);
        
        // Get calendar event and user information
        var calendarEvent = await _calendarEventRepository.GetAsync(input.CalendarEventId);
        var participantUser = await _identityUserRepository.GetAsync(input.IdentityUserId);
        var currentUser = CurrentUser;
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "CalendarInviteUpdated";
        var notificationContentKey = $"CalendarInviteUpdatedMessage|{calendarEvent.Title}|{calendarEvent.StartTime:dd/MM/yyyy HH:mm}|{currentUser?.UserName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.CALENDAR.ToString(),
            HC.Notifications.EventType.CALENDAR_INVITE_UPDATED.ToString(),
            HC.Notifications.RelatedType.CALENDAR_EVENT.ToString(),
            "NORMAL",
            calendarEvent.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.IdentityUserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.IdentityUserId }
            }
        );
        
        return result;
    }
}