using HC.Shared;
using HC.Shared;
using HC.Shared;
using HC.Shared;
using Volo.Abp.Identity;
using HC.WorkflowTemplates;
using HC.WorkflowStepTemplates;
using HC.Workflows;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.WorkflowStepAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.WorkflowStepAssignments;

public class WorkflowStepAssignmentsAppService : WorkflowStepAssignmentsAppServiceBase, IWorkflowStepAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    public WorkflowStepAssignmentsAppService(IWorkflowStepAssignmentRepository workflowStepAssignmentRepository, WorkflowStepAssignmentManager workflowStepAssignmentManager, IDistributedCache<WorkflowStepAssignmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.WorkflowStepTemplates.WorkflowStepTemplate, Guid> workflowStepTemplateRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(workflowStepAssignmentRepository, workflowStepAssignmentManager, downloadTokenCache, workflowStepTemplateRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}