using HC.Shared;
using HC.Shared;
using HC.Shared;
using HC.Shared;
using HC.Departments;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Projects;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.Projects;

public class ProjectsAppService : ProjectsAppServiceBase, IProjectsAppService
{
    //<suite-custom-code-autogenerated>
    public ProjectsAppService(IProjectRepository projectRepository, ProjectManager projectManager, IDistributedCache<ProjectDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Departments.Department, Guid> departmentRepository) : base(projectRepository, projectManager, downloadTokenCache, departmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}