using HC.CalendarEvents;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.CalendarEventParticipants;

public class CalendarEventParticipant : CalendarEventParticipantBase
{
    //<suite-custom-code-autogenerated>
    protected CalendarEventParticipant()
    {
    }

    public CalendarEventParticipant(Guid id, Guid calendarEventId, Guid identityUserId, ParticipantResponse responseStatus, bool notified) : base(id, calendarEventId, identityUserId, responseStatus, notified)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}