using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.CalendarEventParticipants;

public class CalendarEventParticipantManager : CalendarEventParticipantManagerBase
{
    //<suite-custom-code-autogenerated>
    public CalendarEventParticipantManager(ICalendarEventParticipantRepository calendarEventParticipantRepository) : base(calendarEventParticipantRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}