using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.SignatureSettings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.SignatureSettings;

public class SignatureSettingsAppService : SignatureSettingsAppServiceBase, ISignatureSettingsAppService
{
    //<suite-custom-code-autogenerated>
    public SignatureSettingsAppService(ISignatureSettingRepository signatureSettingRepository, SignatureSettingManager signatureSettingManager, IDistributedCache<SignatureSettingDownloadTokenCacheItem, string> downloadTokenCache) : base(signatureSettingRepository, signatureSettingManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}