using HC.Shared;
using HC.Workflows;
using HC.Units;
using HC.MasterDatas;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.Documents;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.Documents;

public class DocumentsAppService : DocumentsAppServiceBase, IDocumentsAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentsAppService(IDocumentRepository documentRepository, DocumentManager documentManager, IDistributedCache<DocumentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.MasterDatas.MasterData, Guid> masterDataRepository, IRepository<HC.Units.Unit, Guid> unitRepository, IRepository<HC.Workflows.Workflow, Guid> workflowRepository) : base(documentRepository, documentManager, downloadTokenCache, masterDataRepository, unitRepository, workflowRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}