using HC.Shared;
using Volo.Abp.Identity;
using HC.WorkflowStepTemplates;
using HC.Documents;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.DocumentAssignments;

public class DocumentAssignmentsAppService : DocumentAssignmentsAppServiceBase, IDocumentAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentAssignmentsAppService(IDocumentAssignmentRepository documentAssignmentRepository, DocumentAssignmentManager documentAssignmentManager, IDistributedCache<DocumentAssignmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Documents.Document, Guid> documentRepository, IRepository<HC.WorkflowStepTemplates.WorkflowStepTemplate, Guid> workflowStepTemplateRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(documentAssignmentRepository, documentAssignmentManager, downloadTokenCache, documentRepository, workflowStepTemplateRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}