using HC.Shared;
using Volo.Abp.Identity;
using HC.WorkflowStepTemplates;
using HC.Documents;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentAssignments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;
using static HC.Notifications.SourceType;
using static HC.Notifications.EventType;
using static HC.Notifications.RelatedType;

namespace HC.DocumentAssignments;

public class DocumentAssignmentsAppService : DocumentAssignmentsAppServiceBase, IDocumentAssignmentsAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.Documents.Document, Guid> _documentRepository;
    protected IRepository<HC.WorkflowStepTemplates.WorkflowStepTemplate, Guid> _workflowStepTemplateRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    
    public DocumentAssignmentsAppService(
        IDocumentAssignmentRepository documentAssignmentRepository, 
        DocumentAssignmentManager documentAssignmentManager, 
        IDistributedCache<DocumentAssignmentDownloadTokenCacheItem, string> downloadTokenCache, 
        IRepository<HC.Documents.Document, Guid> documentRepository, 
        IRepository<HC.WorkflowStepTemplates.WorkflowStepTemplate, Guid> workflowStepTemplateRepository, 
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus) 
        : base(documentAssignmentRepository, documentAssignmentManager, downloadTokenCache, documentRepository, workflowStepTemplateRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _documentRepository = documentRepository;
        _workflowStepTemplateRepository = workflowStepTemplateRepository;
        _identityUserRepository = identityUserRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<DocumentAssignmentDto> CreateAsync(DocumentAssignmentCreateDto input)
    {
        // Call base method to create assignment
        var result = await base.CreateAsync(input);
        
        // Get document, step and user information
        var document = await _documentRepository.GetAsync(input.DocumentId);
        var step = await _workflowStepTemplateRepository.GetAsync(input.StepId);
        var receiverUser = await _identityUserRepository.GetAsync(input.ReceiverUserId);
        var currentUser = CurrentUser;
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "WorkflowAssigned";
        var notificationContentKey = $"WorkflowAssignedMessage|{document.StorageNumber}|{document.Title}|{step.Name}|{currentUser?.UserName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.WORKFLOW.ToString(),
            EventType.WORKFLOW_ASSIGNED.ToString(),
            RelatedType.DOCUMENT.ToString(),
            "NORMAL",
            document.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.ReceiverUserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.ReceiverUserId }
            }
        );
        
        return result;
    }
}