using HC.Shared;
using HC.Projects;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectTasks;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;
using HC.ProjectTaskAssignments;
using HC.ProjectTaskDocuments;

namespace HC.ProjectTasks;

public partial class ProjectTasksAppService : ProjectTasksAppServiceBase, IProjectTasksAppService
{
    private readonly IProjectTaskAssignmentRepository _projectTaskAssignmentRepository;
    private readonly IProjectTaskDocumentRepository _projectTaskDocumentRepository;

    //<suite-custom-code-autogenerated>
    public ProjectTasksAppService(
        IProjectTaskRepository projectTaskRepository,
        ProjectTaskManager projectTaskManager,
        IDistributedCache<ProjectTaskDownloadTokenCacheItem, string> downloadTokenCache,
        IRepository<HC.Projects.Project, Guid> projectRepository,
        IProjectTaskAssignmentRepository projectTaskAssignmentRepository,
        IProjectTaskDocumentRepository projectTaskDocumentRepository)
        : base(projectTaskRepository, projectTaskManager, downloadTokenCache, projectRepository)
    {
        _projectTaskAssignmentRepository = projectTaskAssignmentRepository;
        _projectTaskDocumentRepository = projectTaskDocumentRepository;
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}