using HC.Shared;
using Volo.Abp.Identity;
using HC.Projects;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectMembers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.ProjectMembers;

public class ProjectMembersAppService : ProjectMembersAppServiceBase, IProjectMembersAppService
{
    //<suite-custom-code-autogenerated>
    public ProjectMembersAppService(IProjectMemberRepository projectMemberRepository, ProjectMemberManager projectMemberManager, IDistributedCache<ProjectMemberDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Projects.Project, Guid> projectRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(projectMemberRepository, projectMemberManager, downloadTokenCache, projectRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}