using HC.Shared;
using Volo.Abp.Identity;
using HC.Projects;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.ProjectMembers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Notifications;
using HC.NotificationReceivers;
using Volo.Abp.EventBus.Distributed;
using static HC.Notifications.SourceType;
using static HC.Notifications.EventType;
using static HC.Notifications.RelatedType;

namespace HC.ProjectMembers;

public class ProjectMembersAppService : ProjectMembersAppServiceBase, IProjectMembersAppService
{
    //<suite-custom-code-autogenerated>
    protected INotificationRepository _notificationRepository;
    protected INotificationReceiverRepository _notificationReceiverRepository;
    protected IDistributedEventBus _distributedEventBus;
    protected IRepository<HC.Projects.Project, Guid> _projectRepository;
    protected IRepository<Volo.Abp.Identity.IdentityUser, Guid> _identityUserRepository;
    
    public ProjectMembersAppService(
        IProjectMemberRepository projectMemberRepository, 
        ProjectMemberManager projectMemberManager, 
        IDistributedCache<ProjectMemberDownloadTokenCacheItem, string> downloadTokenCache, 
        IRepository<HC.Projects.Project, Guid> projectRepository, 
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository,
        INotificationRepository notificationRepository,
        INotificationReceiverRepository notificationReceiverRepository,
        IDistributedEventBus distributedEventBus) 
        : base(projectMemberRepository, projectMemberManager, downloadTokenCache, projectRepository, identityUserRepository)
    {
        _notificationRepository = notificationRepository;
        _notificationReceiverRepository = notificationReceiverRepository;
        _distributedEventBus = distributedEventBus;
        _projectRepository = projectRepository;
        _identityUserRepository = identityUserRepository;
    }
    //</suite-custom-code-autogenerated>
    
    // Override CreateAsync to add notification logic
    public override async Task<ProjectMemberDto> CreateAsync(ProjectMemberCreateDto input)
    {
        // Call base method to create member
        var result = await base.CreateAsync(input);
        
        // Get project and user information
        var project = await _projectRepository.GetAsync(input.ProjectId);
        var memberUser = await _identityUserRepository.GetAsync(input.UserId);
        var currentUser = CurrentUser;
        
        // Store localization keys instead of translated text
        // Format: "Key|param1|param2|param3" for Content with parameters
        var notificationTitleKey = "ProjectMemberAdded";
        var notificationContentKey = $"ProjectMemberAddedMessage|{project.Code}|{project.Name}|{currentUser?.UserName ?? L["System"]}";
        
        var notification = new Notification(
            GuidGenerator.Create(),
            notificationTitleKey,
            notificationContentKey,
            SourceType.PROJECT.ToString(),
            EventType.PROJECT_MEMBER_ADDED.ToString(),
            RelatedType.PROJECT.ToString(),
            "NORMAL",
            project.Id.ToString()
        );
        
        notification.TenantId = CurrentTenant.Id;
        await _notificationRepository.InsertAsync(notification);
        
        // Create notification receiver
        var notificationReceiver = new NotificationReceiver(
            GuidGenerator.Create(),
            notification.Id,
            input.UserId,
            false
        );
        notificationReceiver.TenantId = CurrentTenant.Id;
        await _notificationReceiverRepository.InsertAsync(notificationReceiver);
        
        // Publish event to RabbitMQ
        await _distributedEventBus.PublishAsync(
            new NotificationCreatedEto
            {
                NotificationId = notification.Id,
                ReceiverUserIds = new List<Guid> { input.UserId }
            }
        );
        
        return result;
    }
}