using HC.Shared;
using Volo.Abp.Identity;
using HC.Notifications;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.NotificationReceivers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;
using Volo.Abp.Users;

namespace HC.NotificationReceivers;

public class NotificationReceiversAppService : NotificationReceiversAppServiceBase, INotificationReceiversAppService
{
    //<suite-custom-code-autogenerated>
    public NotificationReceiversAppService(INotificationReceiverRepository notificationReceiverRepository, NotificationReceiverManager notificationReceiverManager, IDistributedCache<NotificationReceiverDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Notifications.Notification, Guid> notificationRepository, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) : base(notificationReceiverRepository, notificationReceiverManager, downloadTokenCache, notificationRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>

    public virtual async Task<PagedResultDto<NotificationReceiverWithNavigationPropertiesDto>> GetReadNotificationsAsync(GetUserNotificationsInput input)
    {
        var currentUserId = CurrentUser.GetId();
        var totalCount = await _notificationReceiverRepository.GetCountByUserAndReadStatusAsync(currentUserId, true, input.FilterText);
        var items = await _notificationReceiverRepository.GetNotificationsByUserAndReadStatusAsync(
            currentUserId,
            true,
            input.FilterText,
            input.Sorting,
            input.MaxResultCount,
            input.SkipCount);

        return new PagedResultDto<NotificationReceiverWithNavigationPropertiesDto>
        {
            TotalCount = totalCount,
            Items = ObjectMapper.Map<List<NotificationReceiverWithNavigationProperties>, List<NotificationReceiverWithNavigationPropertiesDto>>(items)
        };
    }

    public virtual async Task<PagedResultDto<NotificationReceiverWithNavigationPropertiesDto>> GetUnreadNotificationsAsync(GetUserNotificationsInput input)
    {
        var currentUserId = CurrentUser.GetId();
        var totalCount = await _notificationReceiverRepository.GetCountByUserAndReadStatusAsync(currentUserId, false, input.FilterText);
        var items = await _notificationReceiverRepository.GetNotificationsByUserAndReadStatusAsync(
            currentUserId,
            false,
            input.FilterText,
            input.Sorting,
            input.MaxResultCount,
            input.SkipCount);

        return new PagedResultDto<NotificationReceiverWithNavigationPropertiesDto>
        {
            TotalCount = totalCount,
            Items = ObjectMapper.Map<List<NotificationReceiverWithNavigationProperties>, List<NotificationReceiverWithNavigationPropertiesDto>>(items)
        };
    }
    //Write your custom code...
}