using HC.Shared;
using Volo.Abp.Identity;
using HC.Notifications;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.NotificationReceivers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Volo.Abp.Users;

namespace HC.NotificationReceivers;

public class NotificationReceiversAppService : NotificationReceiversAppServiceBase, INotificationReceiversAppService
{
    //<suite-custom-code-autogenerated>
    public NotificationReceiversAppService(INotificationReceiverRepository notificationReceiverRepository,
     NotificationReceiverManager notificationReceiverManager, 
     IDistributedCache<NotificationReceiverDownloadTokenCacheItem, string> downloadTokenCache, 
     IRepository<HC.Notifications.Notification, Guid> notificationRepository,
        IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository) 
      : base(notificationReceiverRepository, notificationReceiverManager, downloadTokenCache, notificationRepository, identityUserRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    
    // Mark all unread notifications as read for current user
    public virtual async Task MarkAllAsReadAsync(string? sourceType = null)
    {
        var currentUserId = CurrentUser.Id;
        if (currentUserId == null)
        {
            return;
        }

        // Get all unread notification receivers for current user with navigation properties
        var input = new GetNotificationReceiversInput
        {
            IdentityUserId = currentUserId,
            IsRead = false,
            SourceType = sourceType,
            MaxResultCount = int.MaxValue,
            SkipCount = 0
        };

        var result = await _notificationReceiverRepository.GetListWithNavigationPropertiesAsync(
            input.FilterText,
            input.IsRead,
            input.ReadAtMin,
            input.ReadAtMax,
            input.NotificationId,
            input.IdentityUserId,
            input.Sorting,
            input.MaxResultCount,
            input.SkipCount,
            input.SourceType
        );

        var now = DateTime.UtcNow;

        foreach (var item in result)
        {
            item.NotificationReceiver.IsRead = true;
            item.NotificationReceiver.ReadAt = now;
            await _notificationReceiverRepository.UpdateAsync(item.NotificationReceiver);
        }
    }
}
