using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.WorkflowDefinitions;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.WorkflowDefinitions;

public class WorkflowDefinitionsAppService : WorkflowDefinitionsAppServiceBase, IWorkflowDefinitionsAppService
{
    //<suite-custom-code-autogenerated>
    public WorkflowDefinitionsAppService(IWorkflowDefinitionRepository workflowDefinitionRepository, WorkflowDefinitionManager workflowDefinitionManager, IDistributedCache<WorkflowDefinitionDownloadTokenCacheItem, string> downloadTokenCache) : base(workflowDefinitionRepository, workflowDefinitionManager, downloadTokenCache)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}