using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.MasterDatas;

public class MasterData : MasterDataBase
{
    //<suite-custom-code-autogenerated>
    protected MasterData()
    {
    }

    public MasterData(Guid id, string type, string code, string name, int sortOrder, bool isActive) : base(id, type, code, name, sortOrder, isActive)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}