using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.MasterDatas;

public class MasterDataManager : MasterDataManagerBase
{
    //<suite-custom-code-autogenerated>
    public MasterDataManager(IMasterDataRepository masterDataRepository) : base(masterDataRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}