using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.SurveyLocations;

public class SurveyLocationManager : SurveyLocationManagerBase
{
    //<suite-custom-code-autogenerated>
    public SurveyLocationManager(ISurveyLocationRepository surveyLocationRepository) : base(surveyLocationRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}