using HC.Workflows;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.WorkflowStepTemplates;

public class WorkflowStepTemplate : WorkflowStepTemplateBase
{
    //<suite-custom-code-autogenerated>
    protected WorkflowStepTemplate()
    {
    }

    public WorkflowStepTemplate(Guid id, Guid workflowId, int order, string name, string type, bool allowReturn, bool isActive, int? sLADays = null) : base(id, workflowId, order, name, type, allowReturn, isActive, sLADays)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}