using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.WorkflowStepTemplates;

public class WorkflowStepTemplateManager : WorkflowStepTemplateManagerBase
{
    //<suite-custom-code-autogenerated>
    public WorkflowStepTemplateManager(IWorkflowStepTemplateRepository workflowStepTemplateRepository) : base(workflowStepTemplateRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}