namespace HC.Notifications;

public enum EventType
{
    WORKFLOW_ASSIGNED,
    WORKFLOW_COMPLETED,
    TASK_ASSIGNED,
    TASK_DUE_SOON,
    CHAT_MESSAGE_NEW,
    CALENDAR_INVITED,
    CALENDAR_REMINDER,
    PROJECT_MEMBER_ADDED,
    TASK_ASSIGN_REMOVED,
    PROJECT_MEMBER_REMOVED,
    WORKFLOW_ASSIGN_REMOVED,
    CALENDAR_INVITE_REMOVED,
    TASK_ASSIGN_UPDATED,
    PROJECT_MEMBER_UPDATED,
    WORKFLOW_ASSIGN_UPDATED,
    CALENDAR_INVITE_UPDATED
}