using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.WorkflowDefinitions;

public class WorkflowDefinitionManager : WorkflowDefinitionManagerBase
{
    //<suite-custom-code-autogenerated>
    public WorkflowDefinitionManager(IWorkflowDefinitionRepository workflowDefinitionRepository) : base(workflowDefinitionRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}