using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HC.DocumentAssignments;

public class DocumentAssignmentManager : DocumentAssignmentManagerBase
{
    //<suite-custom-code-autogenerated>
    public DocumentAssignmentManager(IDocumentAssignmentRepository documentAssignmentRepository) : base(documentAssignmentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}