using HC.Documents;
using HC.WorkflowStepTemplates;
using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace HC.DocumentAssignments;

public class DocumentAssignment : DocumentAssignmentBase
{
    //<suite-custom-code-autogenerated>
    protected DocumentAssignment()
    {
    }

    public DocumentAssignment(Guid id, Guid documentId, Guid stepId, Guid receiverUserId, int stepOrder, string actionType, string status, DateTime assignedAt, DateTime processedAt, bool isCurrent) : base(id, documentId, stepId, receiverUserId, stepOrder, actionType, status, assignedAt, processedAt, isCurrent)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}