using HC.Shared;
using HC.Documents;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HC.Permissions;
using HC.DocumentFiles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HC.Shared;

namespace HC.DocumentFiles;

public class DocumentFilesAppService : DocumentFilesAppServiceBase, IDocumentFilesAppService
{
    //<suite-custom-code-autogenerated>
    public DocumentFilesAppService(IDocumentFileRepository documentFileRepository, DocumentFileManager documentFileManager, IDistributedCache<DocumentFileDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HC.Documents.Document, Guid> documentRepository) : base(documentFileRepository, documentFileManager, downloadTokenCache, documentRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}